### ISSUE TITLE
Typos in constant names in opengl.nim

### ISSUE THREAD

**Issue by marcianx** [nim-lang/opengl#10]
In https://github.com/nim-lang/opengl/blob/master/src/opengl.nim
There seem to be a LOT of constants with a stray 'c' in front of them. Eg
cGL_MATRIX_MODE
cGL_TRANSFORM_FEEDBACK_VARYINGS
cGL_SAMPLE_COVERAGE_AR
cGL_TRACK_MATRIX_NV
cGL_COMBINER_INPUT_NV
cGL_TESSELLATION_FACTOR_AMD
cGL_BLEND_EQUATION
cGL_CULL_FACE
This list is not exhaustive.

**Comment by fowlmouth** [comment]
Since some clash and some dont, just make duplicate `c*` consts for the one that dont clash
