### ISSUE TITLE
opengl.nim(73, 20) Error: undeclared identifier: 'LibHandle'

### ISSUE THREAD

**Issue by cyder** [nim-lang/opengl#20]
C:\Nimrod094i386\Nimrod\dist\mingw\bin>..\..\..\bin\nimrod c --app:gui --run ..\..\..\lib\opengl\examples\glut
_example.nim
c:\nimrod094i386\nimrod\config\nimrod.cfg(37, 2) Hint: added path: 'C:\Users\cyder\.babel\pkgs\' [Path]
Hint: used config file 'C:\Nimrod094i386\Nimrod\config\nimrod.cfg' [Conf]
Hint: system [Processing]
Hint: glut_example [Processing]
Hint: glut [Processing]
Hint: opengl [Processing]
Hint: macros [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: sequtils [Processing]
Hint: winlean [Processing]
Hint: os [Processing]
Hint: times [Processing]
Hint: dynlib [Processing]
opengl.nim(73, 20) Error: undeclared identifier: 'LibHandle'

**Comment by EXetoC** [comment]
It is currently recommended to use recent development builds, but it might work with the 0.10.2 release too
