### ISSUE TITLE
Cannot get glCreateShader to work with a context created from glfw

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/opengl#24]
I'm trying to write an OpenGL program using [nim-glfw](https://github.com/EXetoC/nim-glfw/tree/0.2). I guess the problem I observe here has to do with extension loading / context handling. The specific issue is that I cannot create a valid shader using `glCreateShader` (should return a non-zero id in case of success). I have checked that the same does work if I create the window/context using glut (i.e., lower part of the example works). I'm not sure if the issue is caused by `opengl.loadExtensions` or by the nim-glfw package itself, so I'm reporting it here. Maybe I'm also doing something fundamentally wrong creating the context:

    import opengl

    # example using glfw
    when true:
      import glfw/glfw

      # load extensions
      when not defined(useGlew):
        opengl.loadExtensions()

      # create context
      glfw.init()
      var win = newGlWin()

      # try to create a shader
      let shaderId = glCreateShader(GL_VERTEX_SHADER)
      echo "Shader ID: ", shaderId
      assert(shaderId.int != 0)

    # example using glut
    else:
      import glu, glut

      # load extensions
      loadExtensions()

      # create context
      glutInit()
      glutInitDisplayMode(GLUT_DOUBLE)
      glutInitWindowSize(640, 480)
      glutInitWindowPosition(50, 50)
      discard glutCreateWindow("OpenGL Example")

      # try to create a shader
      let shaderId = glCreateShader(GL_VERTEX_SHADER)
      echo "Shader ID: ", shaderId
      assert(shaderId.int != 0)

I also tried to `--define:useGlew` but this results in linker errors (libglew dev library is installed on my system): 

    /tmp/tmp.VhSLf6Irli/opengl_opengl.o: In function `getglerrorcode_115093':
    opengl_opengl.c:(.text+0x1af): undefined reference to `glGetError'
    /tmp/tmp.VhSLf6Irli/opengl_opengl.o: In function `glcreateshader_131007':
    opengl_opengl.c:(.text+0x856): undefined reference to `__glewCreateShader'
    collect2: error: ld returned 1 exit status

I'm using HEAD versions of opengl and nim-glfw, and the latest nim devel version.

**Comment by fowlmouth** [comment]
Added a call to `win.makeContextCurrent` to fix, in searching for an answer I read that glut may delay creating the context until the mainloop function is called? didnt test it.
```nim
glfw/glfw

# create context
glfw.init()
var win = newGlWin()

# load extensions (after context is created)
when not defined(useGlew):
  opengl.loadExtensions()

win.makeContextCurrent

# try to create a shader
let shaderId = glCreateShader(GL_VERTEX_SHADER)
echo "Shader ID: ", shaderId
assert(shaderId.int != 0)
```

**Comment by bluenote10** [comment]
Thanks a lot, works perfectly. And sorry that I wasn't aware of `makeContextCurrent` (never used glfw before).

Regarding the issues with glew: Are these linker problems specific to my system, or is this currently not supported in general?

**Comment by fowlmouth** [comment]
I'm not sure about glew, opengl has its own extension loading that makes glew unnecessary so I've never used it (Araq wrote it so we could avoid glew :p). The makecontextcurrent thing would apply to other libs too
