### ISSUE TITLE
size of GLsizeiptr

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/opengl#25]
I'm currently struggling to get any output from vertex buffer based rendering and I'm trying to find what could be the issue. A possible problem could be the call to `glDrawArrays`, which takes the somewhat unusual `GLsizeiptr` as parameter ([some background on `GLsizeiptr`](http://stackoverflow.com/questions/26758129/glbufferdata-second-arg-is-glsizeiptr-not-glsizei-why)). One thing that confuses me is the size of `GLsizeiptr`, which is defined as `int32` in the bindings. However, in the official [`<GL/glext.h>`](https://www.opengl.org/registry/#headers) header, the definition is `typedef ptrdiff_t GLsizeiptr;`. Running the following quick check

    {.emit: """
    #include <stdio.h>
    #include <stdlib.h>

    void c_call()
    {
      printf("Size of ptrdiff_t: %d\n", sizeof(ptrdiff_t));
    }
    proc c_call() {.importc, nodecl.}
    c_call()
    """}

    # Size of ptrdiff_t: 8

shows on my 64 bit system (Ubuntu 14.04) that the size of `ptrdiff_t` and thus `GLsizeiptr` should be 8.

I have modified the bindings to force `int64` for `GLsizeiptr`, but unfortunately this has not fixed my general issue. I'm also surprised that using an `int32` did not crash in the first place. Therefore I currently don't know which is correct.

**Comment by bluenote10** [comment]
Update: My actual issue is solved. It looks like it does not matter if `GLsizeiptr` set to 32 or 64 bit ints -- both cases have identical behavior in my tests. I have no idea though why both works, nor which one is "more correct".

**Comment by exetoc** [comment]
Probably because it's the last argument, and it'll just happen to work if the 4 bytes that are outside the argument section of the stack are set to zero
