### ISSUE TITLE
extension querying

### ISSUE THREAD

**Issue by ghost** [nim-lang/opengl#26]
`loadExtensions` tries to load every opengl proc that has been referenced, and raises an exception if it fails, so it's currently not possible to implement fallbacks; at least not in a convenient way.

All opengl procs are wrapped (by default), so it might just be a matter of adding more code.

**Comment by krux02** [comment]
I am not a contributer to this package yet, and tried to look into how `loadExtensions` works, because I ran into the same problem, too.  But I couldn't find any information about the `nimLoadProcs0` c call. I don't know what it does, and what it is supposed to do.

**Comment by krux02** [comment]
I found an OpenGL binding generator that supports what you want and it can generate Nim bindings. Maybe that is a good alternative to this binding. It would solve your problem. I know it's a bit late, but yea.

http://glad.dav1d.de/
https://github.com/Dav1dde/glad

**Comment by Araq** [comment]
Fallbacks are not planned.
