### ISSUE TITLE
glMapBuffer doesn't return a pointer

### ISSUE THREAD

**Issue by krux02** [nim-lang/opengl#28]
according to the [specifiction](https://www.opengl.org/sdk/docs/man/html/glMapBuffer.xhtml) glMapBuffer should return a void*. So I guess in Nim it should return a pointer. But for some reason all functions do not return anything.

Here is a list with functions I found in opengl.nim that are related to glMapBuffer, but do not return a pointer as they should.

    glMapNamedBufferRangeEXT
    glMapNamedBufferEXT
    glMapBufferARB
    glMapBufferOES
    glMapBufferRange
    glMapBuffer
    glMapBufferRangeEXT
    glMapBufferRange

There is probably something wrong with the code generator, that does not take the return value of opengl functions into account. It it might be better to fix that, than manually adding the type to all these functions.

**Comment by Araq** [comment]
Nah, the codegen is fine, we didn't really use one iirc and maintain it by hand. Please create PRs, but mark the procs with .discardable so that old code continues to work.

**Comment by krux02** [comment]
Actually I found out, this was fixed in the last commit, but the latest commit is not set to the head yet. I had to manually download the head to fix it in my code. I would really like, if a new version tag is added.

@Araq I generally do agree with you that adding `discardable` is a good behavior for backwards compatibility, but here I would disagree, because any use of these map functions do not make any sense if the result pointer is not used, and any code might have been written that ignores the result pointer can only be wrong. So I would suggest to leave it as it is at the moment, without the discardable result.

**Comment by Araq** [comment]
> So I would suggest to leave it as it is at the moment, without the discardable result.

Ok.

**Comment by ephja** [comment]
@krux02 I'll create a tag

**Comment by ephja** [comment]
done

**Comment by krux02** [comment]
I don't know what you did there, but your tag does not include this important commit this is there in master 3982211732d4e5ce1c898bd14048b044cbe5935a

**Comment by ephja** [comment]
I need to pull more often. How about now?

**Comment by krux02** [comment]
Sorry I kind of forgot this issue, yes it works.
