### ISSUE TITLE
Renaming opengl primitive type constants

### ISSUE THREAD

**Issue by Parashurama** [nim-lang/opengl#32]
Inside the nim opengl module, and due to nim partially ignoring case, there a a few name clashes between functions and constants. As far as I know, this only concern the opengl primitive type constants.
This lead to inconsistency in the naming scheme for this group of constants. (prepending a 'c' to constants with clashing name, but not for others)

``` nim
cGL_UNSIGNED_BYTE
cGL_UNSIGNED_SHORT
cGL_BYTE
cGL_SHORT
cGL_INT
cGL_FLOAT
cGL_FIXED
cGL_DOUBLE

GL_UNSIGNED_INT
GL_INT_2_10_10_10_REV
GL_UNSIGNED_INT_2_10_10_10_REV
GL_UNSIGNED_INT_10F_11F_11F_REV
```

So my proposition is to add the 'c' to all constants in this group, or (and this is my personal preference)
append the suffix "_TYPE" to mark clearly these are used to specify a type to an opengl function.

We would then mark as deprecated the old name for those constants and in sometime later remove them completely.

**Comment by Araq** [comment]
There are few real clashes so adding a prefix/suffix everywhere for consistency is counterproductive, IMO.

**Comment by ephja** [comment]
I think I agree with @Araq. I think that these exceptions should be documented though.

**Comment by krux02** [comment]
I am closing this as rejected. Constants are not renamed when not necessary. If you don't agree on the names you can generate your custom wrapper and choose the names as you like them [here](https://glad.dav1d.de/)
