### ISSUE TITLE
Likely wrong types for GLintptr and GLintptrArb

### ISSUE THREAD

**Issue by Parashurama** [nim-lang/opengl#33]
Currently they both are defined as alias to ``int32``. 
but looking around various specs and the GL/GLES header files on my computer
they are defined this this (in C)
```C
// for MESA and Nvidia  (in GL/gl.h and nvidia/GL/gl.h)
typedef ptrdiff_t GLintptr; 

// for GLES (in GLES2/gl.h )
typedef khronos_intptr_t GLintptr;
#ifdef _WIN64
    typedef signed   long long int khronos_intptr_t;
#else
    typedef signed   long  int     khronos_intptr_t;
#endif
```
``ptrdiff_t`` corresponding roughly to nim's definition of ``int``

So i believe that should be the correct definition
```nim
type
  GLintptr* = int
  GLintptrArb* = int
```

**Comment by Araq** [comment]
Please create a PR and fix it!

**Comment by ephja** [comment]
Thanks. This issue was never closed.
