### ISSUE TITLE
glutBitmapCharacter causes SIGSEGV on macOS

### ISSUE THREAD

**Issue by brechtm** [nim-lang/opengl#53]
Adding the following to glut_example.nim (following `glEnd()  # End of drawing`) causes a segmentation fault:

```
  for character in "text":
    glutBitmapCharacter(GLUT_BITMAP_HELVETICA_10, character.ord)
```

Output:

```
...
CC: opengl_glu
Hint:  [Link]
Hint: operation successful (28380 lines compiled; 1.209 sec total; 60.383MiB peakmem; Debug Build) [SuccessX]
Hint: /private/tmp/glut_example  [Exec]
Traceback (most recent call last)
glut_example.nim(114)    glut_example
glut_example.nim(76)     display
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/private/tmp/glut_example '
```

GDB output:

```
(gdb) r
Starting program: /private/tmp/glut_example
[New Thread 0xf03 of process 8414]
warning: unhandled dyld version (15)
[New Thread 0x1003 of process 8414]
[New Thread 0x1107 of process 8414]
[New Thread 0x1503 of process 8414]
[New Thread 0x2603 of process 8414]
[New Thread 0x2703 of process 8414]
[New Thread 0x2803 of process 8414]
[New Thread 0x2903 of process 8414]

Thread 2 received signal SIGSEGV, Segmentation fault.
0x00007fff48330def in ?? ()
```

Can I make gdb output more useful information?

**Comment by data-man** [comment]
Works for me on the both cards:

>freeglut glutBitmapCharacter: bitmap font 0x00000000 not found. Make sure you're not passing a stroke font.
freeglut glutBitmapCharacter: bitmap font 0x00000000 not found. Make sure you're not passing a stroke font.
freeglut glutBitmapCharacter: bitmap font 0x00000000 not found. Make sure you're not passing a stroke font.
freeglut glutBitmapCharacter: bitmap font 0x00000000 not found. Make sure you're not passing a stroke font.

Nim-devel, ArchLinux x64, gcc 8.1.0, latest opengl module
The first card:

```
GL_VERSION: 3.0 Mesa 18.0.4
GL_SHADING_LANGUAGE_VERSION = 1.30
GLU_VERSION: 1.3
GLU_EXTENSIONS: GLU_EXT_nurbs_tessellator GLU_EXT_object_space_tess 
GLUT_API_VERSION: 4
GLUT_XLIB_IMPLEMENTATION: 13
```

The second card:

```
GL_VERSION: 4.6.0 NVIDIA 396.24
GL_SHADING_LANGUAGE_VERSION = 4.60 NVIDIA
GLU_VERSION: 1.3
GLU_EXTENSIONS: GLU_EXT_nurbs_tessellator GLU_EXT_object_space_tess 
GLUT_API_VERSION: 4
GLUT_XLIB_IMPLEMENTATION: 13
```

**Comment by brechtm** [comment]
The font pointers are also 0 for me. That may not be the cause of the segfault, but I'm sure this not a good thing either.

**Comment by brechtm** [comment]
I did learn that glutBitmapCharacter is [deprecated since macOS 10.9](https://developer.apple.com/library/content/releasenotes/General/APIDiffsMacOSX10_9/GLUT.html) and I'm on 10.13.4. However, compiling and running [this C code](https://www.opengl.org/archives/resources/features/fontsurvey/sooft/examples/glutfonts.tar.gz) from the [Survey Of OpenGL Font Technology](https://www.opengl.org/archives/resources/features/fontsurvey/) does work.
