### ISSUE TITLE
Change in latest nim devel breaks AllErrorCodes

### ISSUE THREAD

**Issue by GrundleTrundle** [nim-lang/opengl#56]
Change:
    https://github.com/nim-lang/Nim/pull/8264

Enums with holes are no longer ordinals, so GLerrorCode can't be in a set anymore.

**Comment by dom96** [comment]
Can we fill the holes? :)

**Comment by GrundleTrundle** [comment]
Hah, probably not.  I'll open a PR when I get a chance.  One use of the set is just to iterate through the values, which is easily replaced by an array of the values.  There's another set (can't remember which off the top of my head) that is testing for membership, but has such a small number of values, an array would suffice there as well.

**Comment by GrundleTrundle** [comment]
I screwed up when looking into this, or I pulled into the wrong directory.  AllErrorCodes was changed from a set a while ago it seems.   Sorry for the false alarm.
