### ISSUE TITLE
Error: undeclared identifier: 'glutGet'

### ISSUE THREAD

**Issue by mrhdias** [nim-lang/opengl#63]
The proc glutGet not exists!
glutGet retrieves simple GLUT state represented by integers.
https://www.opengl.org/resources/libraries/glut/spec3/node70.html

**Comment by krux02** [comment]
How do you reproduce this problem? What platform are you on? Can you post an example program to reproduce the problem?

**Comment by Araq** [comment]
So add it via a PR.
