### ISSUE TITLE
X dependency

### ISSUE THREAD

**Issue by kuon** [nim-lang/opengl#65]
I did a quick read of the code, and X11 seems to be a hard coded dependency on Linux. I'd like to use nim and OpenGL on an embedded system with no X, the OpenGL context is created in a bit of native code. How do you think this library could fit this use case? Could it work without X?

**Comment by krux02** [comment]
Have you tried to use this binding generator: https://glad.dav1d.de/? I use it for my OpenGL Nim project as well.

**Comment by kuon** [comment]
Looks good, I am going to try it

**Comment by Araq** [comment]
I think it's bad that the OpenGL wrapper has no option to disable X11 on Posix.
