### ISSUE TITLE
Please release 1.2.1

### ISSUE THREAD

**Issue by rexim** [nim-lang/opengl#66]
@Araq #61 introduced pretty important fix without which I cannot build my OpenGL application. Could you please release it under 1.2.1 as suggested by @Smittyvb in https://github.com/nim-lang/opengl/pull/61#issuecomment-464463165

Thanks!

**Comment by The-Renaissance** [comment]
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:

**Comment by Neriuzz** [comment]
smh streamer priviledge

**Comment by dom96** [comment]
19 thumbs up in 6 minutes?!? What is going on here?

**Comment by dom96** [comment]
Just tagged 1.2.2 for you.

**Comment by rexim** [comment]
@dom96 it works! Thank you so much!
