### ISSUE TITLE
Add converter?

### ISSUE THREAD

**Issue by itmuckel** [nim-lang/opengl#73]
I just started using this library and to prevent me from type casting integers everywhere I wrote converters:

```nim
converter toGLint*(x: int): GLint = GLint(x)
converter toGLint*(x: GLenum): GLint = GLint(x)
converter toGLsizei*(x: cint): GLsizei = GLSizei(x)
```

There might be more useful converters, I might write them as I need them.

Wouldn't these be a great addition to the wrapper? I imagine everyone would appreciate those.

**Comment by Araq** [comment]
These things are usually not lossless conversions and can introduce subtle bugs.
