### ISSUE TITLE
Strange variable in constant.nim

### ISSUE THREAD

**Issue by ryback08** [nim-lang/opengl#80]
Hello, 
On this file :  opengl/src/opengl/private/constants.nim
https://github.com/nim-lang/opengl/blob/master/src/opengl/private/constants.nim

These constants are not in conformity, there is a "c" in front of

   2    cGL_UNSIGNED_BYTE* = 0x1401.GLenum
   3    cGL_UNSIGNED_SHORT* = 0x1403.GLenum
 628  cGL_FLOAT* = 0x1406.GLenum
1275    cGL_FIXED* = 0x140C.GLenum
3513    cGL_SHORT* = 0x1402.GLenum
4567    cGL_INT* = 0x1404.GLenum

**Comment by Araq** [comment]
Not a bug, in Nim GL_FIXED is the same as GlFixed and similar an OpenGL did not choose names that differ in pronounciation.
