### ISSUE TITLE
glx.nim undeclared identifier: 'XID' w/ nim 2.0.0, x11 1.1

### ISSUE THREAD

**Issue by roverton** [nim-lang/opengl#97]
Upfront: I'm not a nim developer and I have no idea why issue #96 commit has broken the other way.

Was trying to compile a project that depends on this lib under Manjaro and I had to revert all instances of 'XID' back to 'TXID'.

No idea if there's a clean way to handle this discrepancy across versions/distro(?) or not, but I ended up here trying to figure out what was going on and figured it was worth reporting for anyone else who hits the same roadblock.

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-09-16

**Comment by ringabout** [comment]
That's weird, which commit your x11 based on? Are there XID types in your local version x11?

**Comment by roverton** [comment]
x11-1.1-3bee083a8dc900a6c7e4f3b4aaca5f8a6eeae20c  (just noticed that folder name is not commit hash)

commit hash: 30b3a190ef9ec1621c53d501b4da0133281f108e

grep says everything is TXID. No 'XID' found aside from a few function names.

the x11 package was downloaded fresh during the build process. is it possible that the parent project I was building specifically pulled some older x11 package commit? (nim ignorance and all)

**Comment by roverton** [comment]
Welp, I'm zee dummy I guess. Just pulled up that commit has in the nim-lang/x11 and it's super old. I have no idea how the build system decides to pull ancient x11 and brand new opengl, but that's the original project author's problem.

Apologies for the time waster there. Feel free to close with prejudice :)

**Comment by ringabout** [comment]
I don't think that's the latest version of x11. Now I have labelled [the new release](https://github.com/nim-lang/x11/releases/tag/1.2).

>  I was building specifically pulled some older x11 package commit

It's highly likely.

**Comment by ringabout** [comment]
> Apologies for the time waster there.

No problem
